//
// DO NOT MODIFY THIS FILE! It is auto-generated by tools/trey/energy_tables.py
// from docs/trey/species_energy.csv and docs/trey/move_energy.csv.
//

static const struct TreySpeciesEnergyOverride sTreySpeciesEnergyOverrides[] =
{
    { SPECIES_NONE, 0, 0 },
};

static const struct TreyMoveEnergyOverride sTreyMoveEnergyOverrides[] =
{
    { MOVE_NONE, 0 },
};
