#ifndef GUARD_CONSTANTS_TREY_SKY_METATILES_H
#define GUARD_CONSTANTS_TREY_SKY_METATILES_H

// TREY: metatiles of gTileset_TreySky. Generated by tools/trey/sky_art.py --write; do not edit.
// Wall pieces with _XY suffixes are texture variants: paint them by map position (X = x % 2, Y = y % 2).
// Peaks and ridges are multi-metatile pictures: _XY is the column/row inside the picture.

#define METATILE_TreySky_Sky                    0x200
#define METATILE_TreySky_SkyAlt                 0x201
#define METATILE_TreySky_Swirl                  0x202
#define METATILE_TreySky_WindEast               0x203
#define METATILE_TreySky_WindWest               0x204
#define METATILE_TreySky_WindSouth              0x205
#define METATILE_TreySky_WindNorth              0x206
#define METATILE_TreySky_CloudA                 0x207
#define METATILE_TreySky_CloudB                 0x208
#define METATILE_TreySky_CloudC                 0x209
#define METATILE_TreySky_Wall_Center_00         0x20A
#define METATILE_TreySky_Wall_Center_10         0x20B
#define METATILE_TreySky_Wall_Center_01         0x20C
#define METATILE_TreySky_Wall_Center_11         0x20D
#define METATILE_TreySky_Wall_N_00              0x20E
#define METATILE_TreySky_Wall_N_10              0x20F
#define METATILE_TreySky_Wall_S_00              0x210
#define METATILE_TreySky_Wall_S_10              0x211
#define METATILE_TreySky_Wall_W_00              0x212
#define METATILE_TreySky_Wall_W_01              0x213
#define METATILE_TreySky_Wall_E_00              0x214
#define METATILE_TreySky_Wall_E_01              0x215
#define METATILE_TreySky_Wall_Nw                0x216
#define METATILE_TreySky_Wall_Ne                0x217
#define METATILE_TreySky_Wall_Sw                0x218
#define METATILE_TreySky_Wall_Se                0x219
#define METATILE_TreySky_Wall_EndN              0x21A
#define METATILE_TreySky_Wall_EndS              0x21B
#define METATILE_TreySky_Wall_EndW              0x21C
#define METATILE_TreySky_Wall_EndE              0x21D
#define METATILE_TreySky_Wall_Ns                0x21E
#define METATILE_TreySky_Wall_Ew                0x21F
#define METATILE_TreySky_Wall_Single            0x220
#define METATILE_TreySky_Wall_InnerNw           0x221
#define METATILE_TreySky_Wall_InnerNe           0x222
#define METATILE_TreySky_Wall_InnerSw           0x223
#define METATILE_TreySky_Wall_InnerSe           0x224
#define METATILE_TreySky_PeakSmall_00           0x225
#define METATILE_TreySky_PeakSmall_10           0x226
#define METATILE_TreySky_PeakSmall_01           0x227
#define METATILE_TreySky_PeakSmall_11           0x228
#define METATILE_TreySky_PeakLarge_00           0x229
#define METATILE_TreySky_PeakLarge_10           0x22A
#define METATILE_TreySky_PeakLarge_20           0x22B
#define METATILE_TreySky_PeakLarge_01           0x22C
#define METATILE_TreySky_PeakLarge_11           0x22D
#define METATILE_TreySky_PeakLarge_21           0x22E
#define METATILE_TreySky_PeakLarge_02           0x22F
#define METATILE_TreySky_PeakLarge_12           0x230
#define METATILE_TreySky_PeakLarge_22           0x231
#define METATILE_TreySky_RidgeMid_00            0x232
#define METATILE_TreySky_RidgeMid_01            0x233
#define METATILE_TreySky_RidgeLeft_00           0x234
#define METATILE_TreySky_RidgeLeft_01           0x235
#define METATILE_TreySky_RidgeRight_00          0x236
#define METATILE_TreySky_RidgeRight_01          0x237

#endif // GUARD_CONSTANTS_TREY_SKY_METATILES_H
