#!/usr/bin/env python3
"""TREY: turns the Energy override CSVs into C (TREY_PLAN.md 5.6).

  docs/trey/species_energy.csv -> base Energy / Energy EV yield overrides per species
  docs/trey/move_energy.csv    -> Energy cost overrides per move
Writes src/data/trey/energy_overrides.h. Run by the build when either CSV changes.
"""
import csv
import os
import re
import sys

OUT = "src/data/trey/energy_overrides.h"


def read_rows(path):
    with open(path, encoding="utf-8") as f:
        lines = [l for l in f if l.strip() and not l.lstrip().startswith("#")]
    return list(csv.DictReader(lines))


def known_constants(path, prefix):
    with open(path, encoding="utf-8") as f:
        return set(re.findall(r"#define\s+(" + prefix + r"\w+)\b", f.read()))


def main():
    if not os.path.exists("Makefile"):
        print("energy_tables.py: run from the project's root folder.")
        return 1
    errors = []
    species_ok = known_constants("include/constants/species.h", "SPECIES_")
    moves_ok = known_constants("include/constants/moves.h", "MOVE_")

    species_rows = []
    for r in read_rows("docs/trey/species_energy.csv"):
        sp, base, ev = r["species"].strip(), r["base_energy"].strip(), r["energy_ev_yield"].strip()
        if sp not in species_ok:
            errors.append(f"species_energy.csv: unknown species {sp}")
        elif not (base.isdigit() and 1 <= int(base) <= 255):
            errors.append(f"species_energy.csv: {sp}: base_energy must be 1-255")
        elif not (ev.isdigit() and 0 <= int(ev) <= 3):
            errors.append(f"species_energy.csv: {sp}: energy_ev_yield must be 0-3")
        else:
            species_rows.append((sp, int(base), int(ev)))

    move_rows = []
    for r in read_rows("docs/trey/move_energy.csv"):
        mv, cost = r["move"].strip(), r["energy_cost"].strip()
        if mv not in moves_ok:
            errors.append(f"move_energy.csv: unknown move {mv}")
        elif not (cost.isdigit() and 0 <= int(cost) <= 255):
            errors.append(f"move_energy.csv: {mv}: energy_cost must be 0-255")
        else:
            move_rows.append((mv, int(cost)))

    if errors:
        print("TREY Energy tables failed:")
        for e in errors:
            print("  - " + e)
        return 1

    out = ["//", "// DO NOT MODIFY THIS FILE! It is auto-generated by tools/trey/energy_tables.py", "// from docs/trey/species_energy.csv and docs/trey/move_energy.csv.", "//", ""]
    out.append("static const struct TreySpeciesEnergyOverride sTreySpeciesEnergyOverrides[] =\n{")
    for sp, base, ev in species_rows:
        out.append(f"    {{ {sp}, {base}, {ev} }},")
    out.append("    { SPECIES_NONE, 0, 0 },\n};\n")
    out.append("static const struct TreyMoveEnergyOverride sTreyMoveEnergyOverrides[] =\n{")
    for mv, cost in move_rows:
        out.append(f"    {{ {mv}, {cost} }},")
    out.append("    { MOVE_NONE, 0 },\n};\n")
    text = "\n".join(out)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    if not os.path.exists(OUT) or open(OUT, encoding="utf-8").read() != text:
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
